// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/sub/ElementSub.svelte
<script lang="ts">
  export type { ElementSubEnum } from "@lit-internal/test-element-a/sub/element-sub.js";
  import "@lit-internal/test-element-a/sub/element-sub.js";
  import { setProperties, forwardEvents } from "$lib/util.js";
  import type { ElementSubEnum } from "@lit-internal/test-element-a/sub/element-sub.js";
  import type { Snippet } from "svelte";

  export interface Props {
    class?: string;
    style?: string;
    foo?: string | undefined;
    enum?: ElementSubEnum | undefined;
  }
  export interface Events {
    onSubChanged?: (event: CustomEvent<unknown>) => void;
  }
  export interface Slots {
    children?: Snippet;
    stuff?: Snippet;
  }
  const {
    onSubChanged,
    class: className,
    style,
    children,
    stuff,
    ...props
  } = $props<Props & Events & Slots>();
</script>

<element-sub
  use:setProperties={props}
  class={className}
  {style}
  use:forwardEvents={{ "sub-changed": onSubChanged }}
>
  {#if children}
    {@render children()}
  {/if}

  {#if stuff}
    <div slot="stuff">
      {@render stuff()}
    </div>
  {/if}
</element-sub>

// packages/labs/gen-wrapper-vue/goldens/test-element-a/src/sub/ElementSub.vue
<script lang="ts">
export type {ElementSubEnum} from '@lit-internal/test-element-a/sub/element-sub.js';
</script>
<script setup lang="ts">
import {h, useSlots, reactive} from 'vue';
import {assignSlotNodes, Slots} from '@lit-labs/vue-utils/wrapper-utils.js';
import '@lit-internal/test-element-a/sub/element-sub.js';
import {ElementSubEnum} from '@lit-internal/test-element-a/sub/element-sub.js';

export interface Props {
  foo?: string | undefined;
  enum?: ElementSubEnum | undefined;
}

const vueProps = defineProps<Props>();

const defaults = reactive({} as Props);
const vDefaults = {
  created(el: any) {
    for (const p in vueProps) {
      defaults[p as keyof Props] = el[p];
    }
  },
};

let hasRendered = false;

const emit = defineEmits<{
  (e: 'sub-changed', payload: CustomEvent<unknown>): void;
}>();

const slots = useSlots() as Slots;

const render = () => {
  const eventProps = {
    onSubChanged: (event: CustomEvent<unknown>) =>
      emit('sub-changed', event as CustomEvent<unknown>),
  };
  const props = eventProps as typeof eventProps & Props;

  for (const p in vueProps) {
    const v = vueProps[p as keyof Props];
    if (v !== undefined || hasRendered) {
      (props[p as keyof Props] as unknown) = v ?? defaults[p as keyof Props];
    }
  }

  hasRendered = true;

  return h('element-sub', props, assignSlotNodes(slots));
};
</script>
<template><render v-defaults /></template>
