// packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-mixins.ts
import * as React from 'react';
import {createComponent} from '@lit/react';

import {ElementMixins as ElementMixinsElement} from '@lit-internal/test-element-a/element-mixins.js';

export const ElementMixins = createComponent({
  react: React,
  tagName: 'element-mixins',
  elementClass: ElementMixinsElement,
  events: {},
});

// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementMixins.svelte

  <script lang="ts">
    
      import '@lit-internal/test-element-a/element-mixins.js';
      
      
      export interface Props {
     
   }
      export interface Events {
    
  }
      const props = $props<{...Props, ...Events}>();

    </script>
    <element-mixins {...props} >
      
    </element-mixins>
