// packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-without-props.ts
import * as React from 'react';
import {createComponent} from '@lit/react';

import {ElementWithoutProps as ElementWithoutPropsElement} from '@lit-internal/test-element-a/element-without-props.js';

export const ElementWithoutProps = createComponent({
  react: React,
  tagName: 'element-without-props',
  elementClass: ElementWithoutPropsElement,
  events: {},
});

// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementWithoutProps.svelte

  <script lang="ts">
    
      import '@lit-internal/test-element-a/element-without-props.js';
      
      
      export interface Props {
     
   }
      export interface Events {
    
  }
      const props = $props<{...Props, ...Events}>();

    </script>
    <element-without-props {...props} >
      
    </element-without-props>
