// packages/labs/gen-wrapper-react/goldens/test-element-slots/src/element-slots.ts
import * as React from 'react';
import {createComponent, EventName} from '@lit-labs/react';

import {ElementSlots as ElementSlotsElement} from '@lit-internal/test-element-slots/element-slots.js';

export const ElementSlots = createComponent(
  React,
  'element-slots',
  ElementSlotsElement,
  {}
);

// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementSlots.svelte

  <script lang="ts">
    
      import '@lit-internal/test-element-a/element-slots.js';
      
      
      export interface Props {
     mainDefault?: string
   }
      export interface Events {
    
  }
      const props = $props<{...Props, ...Events}>();

    </script>
    <element-slots {...props} >
      
    </element-slots>
