// packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-native-events.ts
import * as React from 'react';
import {createComponent, EventName} from '@lit/react';

import {ElementNativeEvents as ElementNativeEventsElement} from '@lit-internal/test-element-a/element-native-events.js';
import {NativeDetail} from '@lit-internal/test-element-a/element-native-events.js';
export type {NativeDetail} from '@lit-internal/test-element-a/element-native-events.js';

export const ElementNativeEvents = createComponent({
  react: React,
  tagName: 'element-native-events',
  elementClass: ElementNativeEventsElement,
  events: {
    onInput: 'input' as EventName<CustomEvent<NativeDetail>>,
    onValueChanged: 'value-changed' as EventName<CustomEvent<NativeDetail>>,
  },
});

// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementNativeEvents.svelte
<script lang="ts">
  export type { NativeDetail } from "@lit-internal/test-element-a/element-native-events.js";
  import "@lit-internal/test-element-a/element-native-events.js";
  import { setProperties, forwardEvents } from "$lib/util.js";
  import type { NativeDetail } from "@lit-internal/test-element-a/element-native-events.js";
  import type { Snippet } from "svelte";

  export interface Props {
    class?: string;
    style?: string;
    value?: number;
  }
  export interface Events {
    onInput?: (event: CustomEvent<NativeDetail>) => void;
    onValueChanged?: (event: CustomEvent<NativeDetail>) => void;
  }
  export interface Slots {
    children?: Snippet;
  }
  const {
    onInput,
    onValueChanged,
    class: className,
    style,
    children,
    ...props
  } = $props<Props & Events & Slots>();
</script>

<element-native-events
  use:setProperties={props}
  class={className}
  {style}
  use:forwardEvents={{ input: onInput, "value-changed": onValueChanged }}
>
  {#if children}
    {@render children()}
  {/if}
</element-native-events>
