// packages/labs/gen-wrapper-angular/goldens/test-element-a/src/element-mixins.ts
import {Component, ElementRef, NgZone} from '@angular/core';

import type {ElementMixins as ElementMixinsElement} from '@lit-internal/test-element-a/element-mixins.js';
import '@lit-internal/test-element-a/element-mixins.js';

@Component({
  selector: 'element-mixins',
  template: '<ng-content></ng-content>',
})
export class ElementMixins {
  constructor(_e: ElementRef<ElementMixinsElement>, _ngZone: NgZone) {}
}

// packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-mixins.ts
import * as React from 'react';
import {createComponent} from '@lit/react';

import {ElementMixins as ElementMixinsElement} from '@lit-internal/test-element-a/element-mixins.js';

export const ElementMixins = createComponent({
  react: React,
  tagName: 'element-mixins',
  elementClass: ElementMixinsElement,
  events: {},
});
