// packages/labs/gen-wrapper-angular/goldens/test-element-a/element-without-props/src/element-without-props.ts
import {Component, ElementRef, NgZone} from '@angular/core';

import type {ElementWithoutProps as ElementWithoutPropsElement} from '@lit-internal/test-element-a/element-without-props.js';
import '@lit-internal/test-element-a/element-without-props.js';

@Component({
  selector: 'element-without-props',
  template: '<ng-content></ng-content>',
  standalone: true,
  imports: [],
})
export class ElementWithoutProps {
  constructor(_e: ElementRef<ElementWithoutPropsElement>, _ngZone: NgZone) {}
}

// packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-without-props.ts
import * as React from 'react';
import {createComponent} from '@lit/react';

import {ElementWithoutProps as ElementWithoutPropsElement} from '@lit-internal/test-element-a/element-without-props.js';

export const ElementWithoutProps = createComponent({
  react: React,
  tagName: 'element-without-props',
  elementClass: ElementWithoutPropsElement,
  events: {},
});
