// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementSlots.svelte

  <script lang="ts">
    
      import '@lit-internal/test-element-a/element-slots.js';
      
      
      export interface Props {
     mainDefault?: string
   }
      export interface Events {
    
  }
      const props = $props<{...Props, ...Events}>();

    </script>
    <element-slots {...props} >
      
    </element-slots>

// packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-slots.ts
import * as React from 'react';
import {createComponent} from '@lit/react';

import {ElementSlots as ElementSlotsElement} from '@lit-internal/test-element-a/element-slots.js';

export const ElementSlots = createComponent({
  react: React,
  tagName: 'element-slots',
  elementClass: ElementSlotsElement,
  events: {},
});
