// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementWithoutProps.svelte

  <script lang="ts">
    
      import '@lit-internal/test-element-a/element-without-props.js';
      
      
      export interface Props {
     
   }
      export interface Events {
    
  }
      const props = $props<{...Props, ...Events}>();

    </script>
    <element-without-props {...props} >
      
    </element-without-props>

// packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementWithoutProps.vue
<script setup lang="ts">
import {h, useSlots} from 'vue';
import {assignSlotNodes, Slots} from '@lit-labs/vue-utils/wrapper-utils.js';
import '@lit-internal/test-element-a/element-without-props.js';

export interface Props {}

const slots = useSlots();

const render = () => {
  const props = {} as Props;

  return h('element-without-props', props, assignSlotNodes(slots as Slots));
};
</script>
<template><render v-defaults /></template>
