// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementEvents.svelte
<script lang="ts">
  export type { MyDetail } from "@lit-internal/test-element-a/detail-type.js";
  export type { EventSubclass } from "@lit-internal/test-element-a/element-events.js";
  export type { SpecialEvent } from "@lit-internal/test-element-a/special-event.js";
  export type { TemplateResult } from "lit";
  import "@lit-internal/test-element-a/element-events.js";
  import { setProperties, forwardEvents } from "$lib/util.js";
  import type { MyDetail } from "@lit-internal/test-element-a/detail-type.js";
  import type { EventSubclass } from "@lit-internal/test-element-a/element-events.js";
  import type { SpecialEvent } from "@lit-internal/test-element-a/special-event.js";
  import type { TemplateResult } from "lit";
  import type { Snippet } from "svelte";

  export interface Props {
    class?: string;
    style?: string;
    foo?: string | undefined;
  }
  export interface Events {
    onStringCustomEvent?: (event: CustomEvent<string>) => void;
    onNumberCustomEvent?: (event: CustomEvent<number>) => void;
    onMyDetailCustomEvent?: (event: CustomEvent<MyDetail>) => void;
    onEventSubclass?: (event: EventSubclass) => void;
    onSpecialEvent?: (event: SpecialEvent) => void;
    onTemplateResultCustomEvent?: (event: CustomEvent<TemplateResult>) => void;
  }
  export interface Slots {
    children?: Snippet;
  }
  const {
    onStringCustomEvent,
    onNumberCustomEvent,
    onMyDetailCustomEvent,
    onEventSubclass,
    onSpecialEvent,
    onTemplateResultCustomEvent,
    class: className,
    style,
    children,
    ...props
  } = $props<Props & Events & Slots>();
</script>

<element-events
  use:setProperties={props}
  class={className}
  {style}
  use:forwardEvents={{
    "string-custom-event": onStringCustomEvent,
    "number-custom-event": onNumberCustomEvent,
    "my-detail-custom-event": onMyDetailCustomEvent,
    "event-subclass": onEventSubclass,
    "special-event": onSpecialEvent,
    "template-result-custom-event": onTemplateResultCustomEvent,
  }}
>
  {#if children}
    {@render children()}
  {/if}
</element-events>

// packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementEvents.vue
<script lang="ts">
export type {MyDetail} from '@lit-internal/test-element-a/detail-type.js';
export type {EventSubclass} from '@lit-internal/test-element-a/element-events.js';
export type {SpecialEvent} from '@lit-internal/test-element-a/special-event.js';
export type {TemplateResult} from 'lit';
</script>
<script setup lang="ts">
import {h, useSlots, reactive} from 'vue';
import {assignSlotNodes, Slots} from '@lit-labs/vue-utils/wrapper-utils.js';
import '@lit-internal/test-element-a/element-events.js';
import {MyDetail} from '@lit-internal/test-element-a/detail-type.js';
import {EventSubclass} from '@lit-internal/test-element-a/element-events.js';
import {SpecialEvent} from '@lit-internal/test-element-a/special-event.js';
import {TemplateResult} from 'lit';

export interface Props {
  foo?: string | undefined;
}

const vueProps = defineProps<Props>();

const defaults = reactive({} as Props);
const vDefaults = {
  created(el: any) {
    for (const p in vueProps) {
      defaults[p as keyof Props] = el[p];
    }
  },
};

let hasRendered = false;

const emit = defineEmits<{
  (e: 'string-custom-event', payload: CustomEvent<string>): void;
  (e: 'number-custom-event', payload: CustomEvent<number>): void;
  (e: 'my-detail-custom-event', payload: CustomEvent<MyDetail>): void;
  (e: 'event-subclass', payload: EventSubclass): void;
  (e: 'special-event', payload: SpecialEvent): void;
  (
    e: 'template-result-custom-event',
    payload: CustomEvent<TemplateResult>
  ): void;
}>();

const slots = useSlots() as Slots;

const render = () => {
  const eventProps = {
    onStringCustomEvent: (event: CustomEvent<string>) =>
      emit('string-custom-event', event as CustomEvent<string>),
    onNumberCustomEvent: (event: CustomEvent<number>) =>
      emit('number-custom-event', event as CustomEvent<number>),
    onMyDetailCustomEvent: (event: CustomEvent<MyDetail>) =>
      emit('my-detail-custom-event', event as CustomEvent<MyDetail>),
    onEventSubclass: (event: EventSubclass) =>
      emit('event-subclass', event as EventSubclass),
    onSpecialEvent: (event: SpecialEvent) =>
      emit('special-event', event as SpecialEvent),
    onTemplateResultCustomEvent: (event: CustomEvent<TemplateResult>) =>
      emit(
        'template-result-custom-event',
        event as CustomEvent<TemplateResult>
      ),
  };
  const props = eventProps as typeof eventProps & Props;

  for (const p in vueProps) {
    const v = vueProps[p as keyof Props];
    if (v !== undefined || hasRendered) {
      (props[p as keyof Props] as unknown) = v ?? defaults[p as keyof Props];
    }
  }

  hasRendered = true;

  return h('element-events', props, assignSlotNodes(slots));
};
</script>
<template><render v-defaults /></template>
