// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementProps.svelte

  <script lang="ts">
    export type {MyType} from '@lit-internal/test-element-a/element-props.js';
      import '@lit-internal/test-element-a/element-props.js';
      import { setProperties } from "$lib/util.js";
      import type {MyType} from '@lit-internal/test-element-a/element-props.js';
      import type { Snippet } from 'svelte';

      export interface Props {
     class?: string;
     style?: string;
     aStr?: string;
     aNum?: number;
     aBool?: boolean;
     aStrArray?: string[];
     aMyType?: MyType
   }
      export interface Events {
    onAChanged?: (event: CustomEvent<unknown>) => void
  }
      export interface Slots {
  children?: Snippet
}
      const {onAChanged, class: className, style, children, ...props} = $props<Props & Events & Slots>();

    </script>
    <element-props
    use:setProperties={props}
    class={className}
    style={style}
    ona-changed={onAChanged} >
      
    {#if children}
      {@render children()}
    {/if}
    </element-props>

// packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementProps.vue
<script lang="ts">
export type {MyType} from '@lit-internal/test-element-a/element-props.js';
</script>
<script setup lang="ts">
import {h, useSlots, reactive} from 'vue';
import {assignSlotNodes, Slots} from '@lit-labs/vue-utils/wrapper-utils.js';
import '@lit-internal/test-element-a/element-props.js';
import {MyType} from '@lit-internal/test-element-a/element-props.js';

export interface Props {
  aStr?: string;
  aNum?: number;
  aBool?: boolean;
  aStrArray?: string[];
  aMyType?: MyType;
}

const vueProps = defineProps<Props>();

const defaults = reactive({} as Props);
const vDefaults = {
  created(el: any) {
    for (const p in vueProps) {
      defaults[p as keyof Props] = el[p];
    }
  },
};

let hasRendered = false;

const emit = defineEmits<{
  (e: 'a-changed', payload: CustomEvent<unknown>): void;
}>();

const slots = useSlots();

const render = () => {
  const eventProps = {
    onAChanged: (event: CustomEvent<unknown>) =>
      emit('a-changed', event as CustomEvent<unknown>),
  };
  const props = eventProps as typeof eventProps & Props;

  for (const p in vueProps) {
    const v = vueProps[p as keyof Props];
    if (v !== undefined || hasRendered) {
      (props[p as keyof Props] as unknown) = v ?? defaults[p as keyof Props];
    }
  }

  hasRendered = true;

  return h('element-props', props, assignSlotNodes(slots as Slots));
};
</script>
<template><render v-defaults /></template>
