// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementA.svelte

  <script lang="ts">
    
      import '@lit-internal/test-element-a/element-a.js';
      import { setProperties } from "$lib/util.js";
      
      import type { Snippet } from 'svelte';

      export interface Props {
     class?: string;
     style?: string;
     foo?: string | undefined
   }
      export interface Events {
    onAChanged?: (event: CustomEvent<unknown>) => void
  }
      export interface Slots {
  children?: Snippet;
  stuff?: Snippet
}
      const {onAChanged, class: className, style, children, stuff, ...props} = $props<Props & Events & Slots>();

    </script>
    <element-a
    use:setProperties={props}
    class={className}
    style={style}
    ona-changed={onAChanged} >
      {@render children?.()}
<svelte:fragment slot="stuff">{@render stuff?.()}</svelte:fragment>
    </element-a>

// packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementA.vue
<script setup lang="ts">
import {h, useSlots} from 'vue';
import {assignSlotNodes, Slots} from '@lit-labs/vue-utils/wrapper-utils.js';
import '@lit-internal/test-element-a/element-a.js';

const props = defineProps<{
  foo?: string | undefined;
}>();

const emit = defineEmits<{
  (e: 'a-changed', payload: unknown): void;
}>();

const slots = useSlots();

const render = () =>
  h(
    'element-a',
    {
      ...props,
      onAChanged: (event: CustomEvent<unknown>) =>
        emit('a-changed', (event.detail || event) as unknown),
    },
    assignSlotNodes(slots as Slots)
  );
</script>
<template><render /></template>
