// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/ElementCollidingPropAndSlot.svelte
<script lang="ts">
  import "@lit-internal/test-element-a/element-colliding-prop-and-slot.js";
  import { setProperties } from "$lib/util.js";

  import type { Snippet } from "svelte";

  export interface Props {
    class?: string;
    style?: string;
    content?: string;
  }
  export interface Events {}
  export interface Slots {
    contentSnippet?: Snippet;
  }
  const {
    class: className,
    style,
    contentSnippet,
    ...props
  } = $props<Props & Events & Slots>();
</script>

<element-colliding-prop-and-slot
  use:setProperties={props}
  class={className}
  {style}
>
  {#if contentSnippet}
    <div slot="content">
      {@render contentSnippet()}
    </div>
  {/if}
</element-colliding-prop-and-slot>

// packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementCollidingPropAndSlot.vue
<script setup lang="ts">
import {h, useSlots, reactive} from 'vue';
import {assignSlotNodes, Slots} from '@lit-labs/vue-utils/wrapper-utils.js';
import '@lit-internal/test-element-a/element-colliding-prop-and-slot.js';

export interface Props {
  content?: string;
}

const vueProps = defineProps<Props>();

const defaults = reactive({} as Props);
const vDefaults = {
  created(el: any) {
    for (const p in vueProps) {
      defaults[p as keyof Props] = el[p];
    }
  },
};

let hasRendered = false;

const slots = useSlots() as Slots;

const render = () => {
  const eventProps = {};
  const props = eventProps as typeof eventProps & Props;

  for (const p in vueProps) {
    const v = vueProps[p as keyof Props];
    if (v !== undefined || hasRendered) {
      (props[p as keyof Props] as unknown) = v ?? defaults[p as keyof Props];
    }
  }

  hasRendered = true;

  return h('element-colliding-prop-and-slot', props, assignSlotNodes(slots));
};
</script>
<template><render v-defaults /></template>
