// packages/labs/gen-wrapper-react/goldens/test-element-a/src/sub/element-sub.ts
import * as React from 'react';
import {createComponent, EventName} from '@lit/react';

import {ElementSub as ElementSubElement} from '@lit-internal/test-element-a/sub/element-sub.js';

export const ElementSub = createComponent({
  react: React,
  tagName: 'element-sub',
  elementClass: ElementSubElement,
  events: {
    onSubChanged: 'sub-changed' as EventName<CustomEvent<unknown>>,
  },
});

// packages/labs/gen-wrapper-svelte/goldens/test-element-a/src/lib/sub/ElementSub.svelte

  <script lang="ts">
    
      import '@lit-internal/test-element-a/sub/element-sub.js';
      
      
      export interface Props {
     foo?: string | undefined
   }
      export interface Events {
    subChanged: (event: CustomEvent<unknown>) => void
  }
      const props = $props<{...Props, ...Events}>();

    </script>
    <element-sub {...props} >
      
        <slot />
      

      <slot name="stuff" />
    
    </element-sub>
